Create Table students_copy(idno, name, dob, cga, age) as Select idno, name, dob, cgpa, age from students;

/*CREATE TYPE PHONE_T AS OBJECT (A_CODE CHAR(3), P_NUMBER CHAR(8)) instantiable;*/
/*Create Or Replace Type phone_t as object(a_code char(3), p_number char(8));*/

Create Table phone(per_id number(10), per_phone phone_t);

Insert into phone(per_id, per_phone) values (1, phone_t('206','555-1212'));

Select p.per_phone.p_number from phone p where p.per_phone.a_code = '206';

alter table staff add email varchar2(20);

alter table phone rename to phones;

alter table course modify compcode number(5,0);

alter table staff drop email cascade;

alter table students add constraint agecheck check(age > 15);

alter table course drop constraint un_course;

drop table purchases;

CREATE TABLE purchases(orderno INTEGER GENERATED BY DEFAULT AS IDENTITY, vendorid CHAR(5), ordertime DATE TIME);

Create Sequence customers_seq Start With 1000 Increment By 1 Nocache Nocycle;

Select customers_seq.NEXTVAL From Dual;

Select customers_seq.CURRVAL From Dual;

drop table customers;

Create table customers(customer_id number(9) primary key, customer_name char(50));

Insert Into Customers(Customer_id, Customer_name) values (customers_seq.nextval, 'Jiva');

drop table employees cascade;

update Students set name = 'test', email = 'test@yahoo.com' where idno = '2000A7PS001P';

---------------------------------------------------------------------------------------------------------------

drop table category_details;

create table category_details(category_id number(2), category_name varchar2(30));

Insert Into Category_details Values('11', 'Cosmetics');

Insert Into Category_details Values('22', 'Cosmetics');

Insert Into Category_details Values('33', 'Cosmetics');

Insert Into Category_details Values('44', 'Cosmetics');

drop table sub_category_details;

create table sub_category_details(sub_category_id number(2), category_id number(2), sub_category_name varchar2(30));

Insert Into sub_category_details Values('11', '11', 'Cosmetics');

Insert Into sub_category_details Values('22', '22', 'Cosmetics');

Insert Into sub_category_details Values('33', '33', 'Cosmetics');

Insert Into sub_category_details Values('44', '44', 'Cosmetics');

drop table product_details;

create table product_details(product_id number(6), category_id number(2), sub_category_id number(2), product_name varchar2(30));

Select * from category_details;

Select * from sub_category_details;

Select * from product_details;

Alter table Category_details add primary key (category_id);

Alter table Sub_category_details add constraint pk_sub_ca_de primary key(sub_category_id);

Alter table Sub_category_details add constraint fk_sub_cat_cat foreign key(category_id) references Category_details(category_id) On Delete Cascade;

Alter table Product_details add constraint pk_pro_de primary key(product_id);

Alter table Product_details add constraint fk_pro_de_sub_cat foreign key(sub_category_id) references Sub_category_details(sub_category_id) On Delete Cascade;

Alter table Product_details add constraint fk_pro_de_cat foreign key(category_id) references category_details(category_id) On delete cascade;

Alter table Product_details add (price number(2));

Alter table Product_details modify (price number(6,2));

Insert Into Product_details values('123456', '11', '11', 'Lifebuoy Soap', '123.23');

Insert Into Product_details values('123457', '22', '22', 'Nirma Soap', '343.80');

Insert Into Product_details values('123458', '33', '33', 'Cinthol Soap', '167.96');

Insert Into Product_details values('123459', '44', '44', 'Rexona Soap', '156.12');

Alter table Product_details drop (price);

Alter table Product_details drop (Brand_name);

Alter table Product_details add (Brand_name varchar2(20));

Update Product_details set Brand_name = 'HUL';

Alter table product_details modify(Brand_name varchar(20) not null);

Drop table category_dt;

Alter table Category_details rename to category_dt;

Select * From user_tables;

Delete * From user_tables;